### ISSUE TITLE
Dockerfile Build Error

### ISSUE THREAD

**Issue by xdubx** [larueli/decidim-nonroot#7]
Hey, 
i tryed to build the container for myself. This error comes by docker.

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/usr/local/bundle/ruby/2.6.0/gems/unf_ext-0.0.7.7/ext/unf_ext
/usr/local/bin/ruby -I /usr/local/lib/ruby/2.6.0 -r
./siteconf20201109-13571-lydyl8.rb extconf.rb
checking for -lstdc++... yes
creating Makefile

current directory: /usr/local/bundle/ruby/2.6.0/gems/unf_ext-0.0.7.7/ext/unf_ext
make "DESTDIR=" clean

current directory: /usr/local/bundle/ruby/2.6.0/gems/unf_ext-0.0.7.7/ext/unf_ext
make "DESTDIR="
compiling unf.cc
cc1plus: warning: command line option '-Wdeclaration-after-statement' is valid
for C/ObjC but not for C++
cc1plus: warning: command line option '-Wimplicit-function-declaration' is valid
for C/ObjC but not for C++
cc1plus: warning: command line option '-Wimplicit-int' is valid for C/ObjC but
not for C++
virtual memory exhausted: Cannot allocate memory
make: *** [Makefile:213: unf.o] Error 1

make failed, exit code 2

Gem files will remain installed in
/usr/local/bundle/ruby/2.6.0/gems/unf_ext-0.0.7.7 for inspection.
Results logged to
/usr/local/bundle/ruby/2.6.0/extensions/x86_64-linux/2.6.0/unf_ext-0.0.7.7/gem_make.out

An error occurred while installing unf_ext (0.0.7.7), and Bundler cannot
continue.
Make sure that `gem install unf_ext -v '0.0.7.7' --source
'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  decidim-dev was resolved to 0.22.0, which depends on
    decidim was resolved to 0.22.0, which depends on
      decidim-accountability was resolved to 0.22.0, which depends on
        decidim-comments was resolved to 0.22.0, which depends on
          decidim-core was resolved to 0.22.0, which depends on
            etherpad-lite was resolved to 0.3.0, which depends on
              rest-client was resolved to 2.1.0, which depends on
                http-cookie was resolved to 1.0.3, which depends on
                  domain_name was resolved to 0.5.20190701, which depends on
                    unf was resolved to 0.1.4, which depends on
                      unf_ext
        gsub  config/boot.rb
      append  .gitignore
      remove  public/404.html
      remove  public/500.html
      create  config/initializers/decidim.rb
       route  mount Decidim::Core::Engine => '/'
      append  db/seeds.rb
      create  config/initializers/carrierwave.rb
      create  config/initializers/social_share_button.rb
      create  config/secrets.yml
      remove  app/views/layouts/application.html.erb
      remove  app/views/layouts/mailer.text.erb
      append  app/assets/javascripts/application.js
        gsub  app/assets/javascripts/application.js
      insert  app/assets/stylesheets/application.css
      create  app/assets/stylesheets/decidim.scss
      insert  config/environments/development.rb
      insert  config/environments/test.rb
        gsub  config/environments/production.rb
      insert  config/environments/production.rb
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/resolver.rb:290:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'decidim (= 0.22.0)' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)
	from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/resolver.rb:258:in `each'
	from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/resolver.rb:258:in `verify_gemfile_dependencies_are_found!'
	from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/resolver.rb:49:in `start'
	from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/resolver.rb:22:in `resolve'
	from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/definition.rb:258:in `resolve'
	from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/definition.rb:170:in `specs'
	from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/definition.rb:237:in `specs_for'
	from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/definition.rb:226:in `requested_specs'
	from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/runtime.rb:101:in `block in definition_method'
	from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/runtime.rb:20:in `setup'
	from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler.rb:149:in `setup'
	from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `block in <top (required)>'
	from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:136:in `with_level'
	from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:88:in `silence'
	from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `<top (required)>'
	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /decidim-app/config/boot.rb:3:in `<top (required)>'
	from bin/rails:3:in `require_relative'
	from bin/rails:3:in `<main>'
The command '/bin/sh -c apt-get update && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - &&     echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list &&     apt-get update && apt-get install -y nodejs imagemagick yarn libicu-dev postgresql-client openssl nano bash curl git && apt-get autoremove &&     mkdir -m 770 /home/docker-user &&     gem install bundler && gem install bootsnap && gem install listen && mkdir -m 770 /decidim-app && gem install decidim -v ${DECIDIM_VERSION} && decidim /decidim-app' returned a non-zero code: 1

```

**Comment by xdubx** [comment]
Oh i forget to enter some memory limit parameters :+1:
